//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Micro.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class List
    {
        public int id_micro { get; set; }
        public Nullable<int> id_box { get; set; }
        public Nullable<int> id_PropertyType { get; set; }
        public Nullable<int> id_card { get; set; }
        public Nullable<int> id_symbol { get; set; }
        public Nullable<int> cabinet_number { get; set; }
        public string floor { get; set; }
    
        public virtual Box Box { get; set; }
        public virtual Card Card { get; set; }
        public virtual PropertyType PropertyType { get; set; }
        public virtual Symbol Symbol { get; set; }
    }
}
