//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Micro.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MicroPoiskEntities1 : DbContext
    {
        public MicroPoiskEntities1()
            : base("name=MicroPoiskEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Box> Boxes { get; set; }
        public virtual DbSet<Card> Cards { get; set; }
        public virtual DbSet<List> Lists { get; set; }
        public virtual DbSet<PropertyType> PropertyTypes { get; set; }
        public virtual DbSet<Symbol> Symbols { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
